### ISSUE TITLE
Initial docker-compose

### ISSUE THREAD

**Issue by sheiely** [marcusnogueiraa/concord#14]
Create docker-compose with Spring and Postgres Image.

**Comment by sheiely** [comment]
@marcusnogueiraa can you review?

**Comment by marcusnogueiraa** [comment]
Everything is fine, my daughter. Later, as the application grows, we have to add Redis and MongoDB Images to Docker Compose. There will be a task in the Backlog for this. For now, everything is OK. Thanks for the contribution =) 
@sheiely 

I'm closing the issue.
