### ISSUE TITLE
Design WebSockets Architecture

### ISSUE THREAD

**Issue by sheiely** [marcusnogueiraa/concord#6]
- [x] add listener
- [x] add event entity
- [x] modify handler
- [x] add handler to event channel message
- [x] user can send messages for other users e others channels
- [x] user can receive messages

**Comment by marcusnogueiraa** [comment]
What types of websocket messages will be handled by the server?
Write in ENUM format

**Comment by marcusnogueiraa** [comment]
USER_MESSAGE 
CHANNEL_MESSAGE 
FRIEND_REQUEST
USER_STATUS

**Comment by marcusnogueiraa** [comment]
Message Entity Fields:

**Type**
**Data**
